### ISSUE TITLE
Double callbacks call donation amount to double

### ISSUE THREAD

**Issue by samkio** [DP94/DonateCraftPlugin#16]

**Comment by samkio** [comment]
I can't re-create this locally after some testing. Does this issue still exist? @DP94 did you have an idea of what may have caused the duplication?

**Comment by DP94** [comment]
Hmm not sure. I'll see if i can re-create it again

**Comment by DP94** [comment]
I think this must have been fixed recently with all the changes to the callback logic. I also made tweaks to the angular sum code too. I hardcoded the status as pending (as i can't seem to get anything other than "Accepted" now) and it all seems to be OK.
